config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :themes
  resources :details
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :members
  resources :abouts
  resources :contacts
  resources :tutorials
  resources :homes

  root 'homes#index'
end

app/models/about.rb
class About < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :message, presence: true
end

app/models/detail.rb
class Detail < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
  validates :username, uniqueness: true, presence: true
  validates :email, uniqueness: true, presence: true, format: /\A[^@]+@[^@]+\z/
end

app/models/home.rb
class Home < ApplicationRecord
  validates :event, presence: true
  validates :date_time, presence: true
  validates :venue, presence: true
  validates :body, presence: true
end

app/models/member.rb
class Member < ApplicationRecord
  validates :username, presence: true
  validates :email, uniqueness: true, presence: true, format: /\A[^@]+@[^@]+\z/
end

app/models/theme.rb
class Theme < ApplicationRecord
end

app/models/tutorial.rb
class Tutorial < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  validates :code, presence: true
  validates :video, presence: true
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  before_action :set_about, only: [:show, :edit, :update, :destroy]

  def index
    @abouts = About.all
  end

  def show
    @about = About.find(params[:id])
    @abouts = About.order('created_at desc').limit(4).offset(1)
  end

  def new
    @about = About.new
  end

  def create
    @about = About.new(about_params)

    respond_to do |format|
      if @about.save
        format.html { redirect_to @about, notice: 'About was successfully created.' }
        format.json { render :show, status: :created, location: @about }
      else
        format.html { flash[:failure!] = 'About Not created! Verify Details & Send Again!' }
        format.html { render 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @about.update(about_params)
        format.html { redirect_to @about, notice: 'About was successfully updated.' }
        format.json { render :show, status: :ok, location: @about }
      else
        format.html { render :edit }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @about.destroy
    respond_to do |format|
      format.html { redirect_to abouts_url, notice: 'About was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_about
      @about = About.find(params[:id])
    end

    def about_params
      params.require(:about).permit(:title, :body)
    end
end

app/controllers/events_controller.rb
class EventsController < InheritedResources::Base
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html do
          flash[:success] = 'Successfully Done'
          redirect_to events_url
        end
      else
        format.html { flash[:failure!] = 'Error! Verify Details!' }
        format.html { render 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html do
          flash[:success] = 'Successfully Updated'
          redirect_to events_url
        end
      else
        format.html { flash[:failure!] = 'Error! Verify Details!' }
        format.html { render 'new' }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to event_url, notice: 'Successfully Destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:username, :email, :confirm)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  def index
    @homes = Home.all
  end

  def show
    @home = Home.find(params[:id])
    @homes = Home.order('created_at desc').limit(4).offset(1)
  end

  def new
    @home = Home.new
  end

  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home Details successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { flash[:failure!] = 'Home Details Not created! Verify Details & Send Again!' }
        format.html { render 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_home
      @home = Home.find(params[:id])
    end

    def home_params
      params.require(:home).permit(:event, :date_time, :venue, :body)
    end
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  before_action :set_tutorial, only: [:show, :edit, :update, :destroy]

  def index
    @tutorials = Tutorial.all
  end

  def show
    @tutorial = Tutorial.find(params[:id])
    @tutorials = Tutorial.order('created_at desc').limit(4).offset(1)
  end

  def new
    @tutorial = Tutorial.new
  end

  def edit
  end

  def create
    @tutorial = Tutorial.new(tutorial_params)

    respond_to do |format|
      if @tutorial.save
        format.html { redirect_to @tutorial, notice: 'Tutorial Details successfully created.' }
        format.json { render :show, status: :created, location: @tutorial }
      else
        format.html { flash[:failure!] = 'Tutorial Details Not created! Verify Details & Send Again!' }
        format.html { render 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @tutorial.update(tutorial_params)
        format.html { redirect_to @tutorial, notice: 'Tutorial was successfully updated.' }
        format.json { render :show, status: :ok, location: @tutorial }
      else
        format.html { render :edit }
        format.json { render json: @tutorial.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tutorial.destroy
    respond_to do |format|
      format.html { redirect_to tutorials_url, notice: 'Tutorial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_tutorial
      @tutorial = Tutorial.find(params[:id])
    end

    def tutorial_params
      params.require(:tutorial).permit(:title, :body, :code, :video)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/views/tutorials/_form.html.erb
<%= form_with(model: tutorial, local: true) do |form| %>
  <% if tutorial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tutorial.errors.count, "error") %> prohibited this tutorial from being saved:</h2>

      <ul>
      <% tutorial.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :video %>
    <%= form.text_field :video %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tutorials/edit.html.erb
<h1>Editing Tutorial</h1>

<%= render 'form', tutorial: @tutorial %>

<%= link_to 'Show', @tutorial %> |
<%= link_to 'Back', tutorials_path %>

app/views/tutorials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tutorials</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Code</th>
      <th>Video</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tutorials.each do |tutorial| %>
      <tr>
        <td><%= tutorial.title %></td>
        <td><%= tutorial.body %></td>
        <td><%= tutorial.code %></td>
        <td><%= tutorial.video %></td>
        <td><%= link_to 'Show', tutorial %></td>
        <td><%= link_to 'Edit', edit_tutorial_path(tutorial) %></td>
        <td><%= link_to 'Destroy', tutorial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tutorial', new_tutorial_path %>

app/views/tutorials/new.html.erb
<h1>New Tutorial</h1>

<%= render 'form', tutorial: @tutorial %>

<%= link_to 'Back', tutorials_path %>

app/views/tutorials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @tutorial.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @tutorial.body %>
</p>

<p>
  <strong>Code:</strong>
  <%= @tutorial.code %>
</p>

<p>
  <strong>Video:</strong>
  <%= @tutorial.video %>
</p>

<%= link_to 'Edit', edit_tutorial_path(@tutorial) %> |
<%= link_to 'Back', tutorials_path %>