config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :themes
  resources :details
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :members
  resources :abouts
  resources :contacts
  resources :tutorials
  resources :homes

  root 'homes#index'
end

app/models/about.rb
class About < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :message, presence: true
end

app/models/detail.rb
class Detail < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
  validates :username, uniqueness: true, presence: true
  validates :email, uniqueness: true, presence: true, format: /\A[^@]+@[^@]+\z/
end

app/models/home.rb
class Home < ApplicationRecord
  validates :event, presence: true
  validates :date_time, presence: true
  validates :venue, presence: true
  validates :body, presence: true
end

app/models/member.rb
class Member < ApplicationRecord
  validates :username, presence: true
  validates :email, uniqueness: true, presence: true, format: /\A[^@]+@[^@]+\z/
end

app/models/theme.rb
class Theme < ApplicationRecord
end

app/models/tutorial.rb
class Tutorial < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  validates :code, presence: true
  validates :video, presence: true
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  before_action :set_about, only: [:show, :edit, :update, :destroy]

  def index
    @abouts = About.all
  end

  def show
    @about = About.find(params[:id])
    @abouts = About.order('created_at desc').limit(4).offset(1)
  end

  def new
    @about = About.new
  end

  def create
    @about = About.new(about_params)

    respond_to do |format|
      if @about.save
        format.html { redirect_to @about, notice: 'About was successfully created.' }
        format.json { render :show, status: :created, location: @about }
      else
        format.html { flash[:failure!] = 'About Not created! Verify Details & Send Again!' }
        format.html { render 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @about.update(about_params)
        format.html { redirect_to @about, notice: 'About was successfully updated.' }
        format.json { render :show, status: :ok, location: @about }
      else
        format.html { render :edit }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @about.destroy
    respond_to do |format|
      format.html { redirect_to abouts_url, notice: 'About was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_about
      @about = About.find(params[:id])
    end

    def about_params
      params.require(:about).permit(:title, :body)
    end
end

app/controllers/events_controller.rb
class EventsController < InheritedResources::Base
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html do
          flash[:success] = 'Successfully Done'
          redirect_to events_url
        end
      else
        format.html { flash[:failure!] = 'Error! Verify Details!' }
        format.html { render 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html do
          flash[:success] = 'Successfully Updated'
          redirect_to events_url
        end
      else
        format.html { flash[:failure!] = 'Error! Verify Details!' }
        format.html { render 'new' }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to event_url, notice: 'Successfully Destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:username, :email, :confirm)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  def index
    @homes = Home.all
  end

  def show
    @home = Home.find(params[:id])
    @homes = Home.order('created_at desc').limit(4).offset(1)
  end

  def new
    @home = Home.new
  end

  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home Details successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { flash[:failure!] = 'Home Details Not created! Verify Details & Send Again!' }
        format.html { render 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_home
      @home = Home.find(params[:id])
    end

    def home_params
      params.require(:home).permit(:event, :date_time, :venue, :body)
    end
end

app/controllers/themes_controller.rb
class ThemesController < InheritedResources::Base

  private

    def theme_params
      params.require(:theme).permit(:title, :demo_link, :download_link)
    end

end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/views/abouts/_form.html.erb
<%= form_with(model: about, local: true) do |form| %>
  <% if about.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(about.errors.count, "error") %> prohibited this about from being saved:</h2>

      <ul>
      <% about.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/abouts/edit.html.erb
<h1>Editing About</h1>

<%= render 'form', about: @about %>

<%= link_to 'Show', @about %> |
<%= link_to 'Back', abouts_path %>

app/views/abouts/index.html.erb
<!-- Header -->
<header class="w3-display-container w3-content" style="max-width:100%;">
  <div class="w3-display-container">
    <img src="assets/about_banner.png" alt="About Image" class="w3-image w3-opacity w3-hover-opacity-off" style="min-height: 100%;background-attachment: fixed; background-position: center; background-repeat: no-repeat; background-size: cover;">

    <div class="w3-display-middle w3-padding-large w3-border w3-round-xlarge w3-wide w3-text-white w3-center w3-hide-small">
      <h2><b>ABOUT</b></h2>
    </div>

    <div class="w3-display-middle w3-border w3-round-large w3-wide w3-text-white w3-center w3-hide-medium w3-hide-large">
      <h4><b>ABOUT</b></h4>
    </div>
  </div>
</header>

<!-- Content -->
<div class="w3-row-padding w3-light-grey w3-padding-64 w3-container">
  <div class="w3-content">
    <div class="w3-third w3-right w3-border w3-round-xlarge w3 wide" style="background-color:#070e1d; padding-left: 15px; padding-right: 15px;">
      <img src="assets/falls_pic.png" class="w3-circle" style="width:50%" alt="Elly Ambet">
      <p class="w3-padding-16 w3-text-light-grey">
        <b><i>RuiruTech</i></b><br>
        <i>One step at a time...</i><br>
        <b class="fa fa-twitter"></b> <i>@RuiruTech</i>
        <b class="fa fa-github"></b> <i>github.com/ruirutech</i>
      </p>
      <p class="w3-padding-16" style="color:#25bdd6;">
        <b class="fa fa-microphone"></b> <b>"...If you bring a group of smart people to a room for the porpose of coming up with numerous mind blowing ideas, you will not be disappointed. When you embark on bringing these ideas to life, that will be a challenging expedition. Only the ones which are successfully excecuted are valuable. This proves that an idea in itself isn't valuable..."<br> "...Simple ideas that are brought to excecution are worth more than brilliant ideas that have never been worked on..."</b>
      </p>
    </div>
    <div class="w3-twothird" style="color:#070e1d;">
      <% @abouts.each do |about| %>
        <h3><b><%= about.title %></b></h3>
        <h5 class="w3-padding-32"><%= about.body %></h5>
      <% end %>
    </div>
  </div>
</div>

app/views/abouts/new.html.erb
<h1>New About</h1>

<%= render 'form', about: @about %>

<%= link_to 'Back', abouts_path %>

app/views/abouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @about.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @about.body %>
</p>

<%= link_to 'Edit', edit_about_path(@about) %> |
<%= link_to 'Back', abouts_path %>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :confirm %>
    <%= form.check_box :confirm %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<!-- Content Container -->
<div class="w3-container w3-padding-16 w3-theme-l5 w3-light-grey">
  <div class="w3-col m5 w3-hide-small" style="background-color: #25bdd6; margin-left: 30%;">
    <div class="w3-padding-16 w3-center">
      <span class="w3-xlarge w3-text-black"><b>Are You Attending The Event??</b></span>
    </div>
    <h5 class="w3-center" style="color: #070e1d;"><i>Please Confirm!!</i></h5>
    <%= form_for Event.new, url: {action: "create"}, html: {class: "w3-container w3-padding-16 w3-white"} do |f| %>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>" style="color: #13a726;"><%= value %></div>
      <% end %>
      <div class="w3-section"> 
        <%= f.text_field :username, class: 'w3-input', placeholder: 'UserName'%>
      </div>
      <div class="w3-section">      
        <%= f.text_field :email, class: 'w3-input', placeholder: 'Email'%>
      </div>
      <div class="w3-row w3-padding-32 w3-text-grey">
        <h4>Confirm Attendance!!</h4>
        <div class="w3-half">
          <i><%= f.radio_button :confirm, "1" %> <%= f.label :confirm, "Yes" %></i>
        </div>
        <div class="w3-half">
          <i><%= f.radio_button :confirm, "0" %> <%= f.label :confirm, "No" %></i>
        </div>
      </div>
      <button type="submit" class="w3-button w3-round-large w3-theme fa fa-user" style="background-color: #07879c; color: #ffff"> RSVP</button>
    <% end %>
  </div>
</div>

<div class="w3-container w3-padding-16 w3-theme-l5 w3-light-grey">
  <div class="w3-col m5 w3-hide-medium w3-hide-large" style="background-color: #25bdd6;">
    <div class="w3-padding-16 w3-center">
      <span class="w3-xlarge w3-text-black"><b>Are You Attending The Event??</b></span>
    </div>
    <h5 class="w3-center" style="color: #070e1d;"><i>Please Confirm!!</i></h5>
    <%= form_for Event.new, url: {action: "create"}, html: {class: "w3-container w3-padding-16 w3-white"} do |f| %>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>" style="color: #13a726;"><%= value %></div>
      <% end %>
      <div class="w3-section"> 
        <%= f.text_field :username, class: 'w3-input', placeholder: 'UserName'%>
      </div>
      <div class="w3-section">      
        <%= f.text_field :email, class: 'w3-input', placeholder: 'Email'%>
      </div>
      <div class="w3-row w3-padding-32 w3-text-grey">
        <h4>Confirm Attendance!!</h4>
        <div class="w3-half">
          <i><%= f.radio_button :confirm, "1" %> <%= f.label :confirm, "Yes" %></i>
        </div>
        <div class="w3-half">
          <i><%= f.radio_button :confirm, "0" %> <%= f.label :confirm, "No" %></i>
        </div>
      </div>
      <button type="submit" class="w3-button w3-round-large w3-theme fa fa-user" style="background-color: #07879c; color: #ffff"> RSVP</button>
    <% end %>
  </div>
</div>

<!-- Table Section -->
<div class="w3-container w3-padding-32 w3-theme-l5 w3-white">
  <h3 class="w3-center">People Attending The Event</h3>
  <table class="w3-table-all w3-hide-small" style="width:80%; margin-left: 10%;">
    <tr style="background-color: #25bdd6;">
      <th><b>Username</b></th>
      <th><b>Email</b></th>
      <th><b>Status</b></th>
      <th><b>Change Status</b></th>
    </tr>
    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= event.username %></td>
          <td><%= event.email %></td> 
          <td>
            <% if event.confirm == true %>
              <b class="w3-text-green fa fa-check"> Confirmed</b>
            <% elsif event.confirm == nil %>
              <b class="w3-text-grey fa fa-stop-circle"> No Choice Made!</b>
            <% else %>
              <b class="w3-text-indigo fa fa-times"> Not Confirmed!</b>
            <% end %>
          </td>
          <td>
            <% if event.confirm == false %>
              <%= form_with(model: event, local: true) do |form| %>
                <div class="checkbox_field">
                  <%= form.check_box :confirm, checked: true %>
                </div>
                <button type="submit" class="w3-button w3-round-large w3-theme" style="background-color: #07879c; color: #ffff">Confirm?</button>
              <% end %>
            <% elsif event.confirm == nil %>
              <%= form_with(model: event, local: true) do |form| %>
                <div class="checkbox_field">
                  <%= form.check_box :confirm, checked: true %>
                </div>
                <button type="submit" class="w3-button w3-round-large w3-theme" style="background-color: #b8436d; color: #ffff">Make A Choice!</button>
              <% end %>
            <% else %>
              <%= form_with(model: event, local: true) do |form| %>
                <div class="checkbox_field">
                  <%= form.check_box :confirm, checked: false %>
                </div>
                <button type="submit" class="w3-button w3-round-large w3-theme" style="background-color: #292d2e; color: #ffff">Unconfirm?</button>
              <% end %>
            <% end %>
          </td>      
        </tr> 
      <% end %>
    </tbody>
  </table>

  <table class="w3-table w3-bordered w3-striped w3-border w3-hoverable w3-hide-medium w3-hide-large">
    <tr style="background-color: #25bdd6;">
      <th>Username</th>
      <th>Email</th>
    </tr>
    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><i><%= event.username %></i></td>
          <td><i><%= event.email %></i></td>
        </tr> 
      <% end %>
    </tbody>
  </table>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @event.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @event.email %>
</p>

<p>
  <strong>Confirm:</strong>
  <%= @event.confirm %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/homes/_form.html.erb
<%= form_with(model: home, local: true) do |form| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :event %>
    <%= form.text_field :event %>
  </div>

  <div class="field">
    <%= form.label :date_time %>
    <%= form.datetime_select :date_time %>
  </div>

  <div class="field">
    <%= form.label :venue %>
    <%= form.text_field :venue %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<!-- Header -->
<header class="w3-display-container w3-content" style="max-width:100%;">
  <div class="w3-display-container">
    <img src="assets/home_banner.png" alt="Home Image" class="w3-image w3-opacity w3-hover-opacity-off" style="min-height: 100%;background-attachment: fixed; background-position: center; background-repeat: no-repeat; background-size: cover;">

    <!-- Info Section medium & large screens -->
    <div class="w3-display-middle w3-border w3-round-xlarge w3-wide w3-opacity w3-text-white w3-center w3-hide-small" style="background-color:#0a0d15; padding-left: 15px; padding-right: 15px;">
      <h4><b class="w3-hide-medium" style="color: #25bdd6;">RuiruTech...One Step At A Time</b></h4>
      <h5><b><i>The Tech Community</i></b></h5>
        <a href="details" class="w3-button w3-round-large w3-ripple w3-dark-grey"><i class="fa fa-info-circle"></i><b> MORE</b></a>
        <a href="members" class="w3-button w3-round-large w3-ripple" style="background-color: #25bdd6; color: #ffff;"><i class="fa fa-users"></i><b> JOIN</b></a>
      </p>
    </div>

    <div class="w3-display-middle w3-border w3-round-large w3-opacity w3-text-white w3-center w3-hide-large w3-hide-medium" style="background-color:#0a0d15; padding-left: 5px; padding-right: 5px;">
      <p><b><i>Are You Into Tech?</i></b></p>
      <p>
        <a href="members" class="w3-button w3-round-large w3-ripple" style="background-color: #25bdd6; color: #ffff;"><i class="fa fa-users"></i> <b>JOIN THE COMMUNITY</b></a>
      </p>
    </div>
  </div>
</header>

<!-- body content -->
<div class="w3-container w3-content w3-padding-16">
  <div class="w3-centre">
    <div class="w3-container" style="background-color:#0a0d15; color: #ffff; ">
      <h4 class="link-hovered"><i class="fa fa-newspaper-o w3-margin-right"></i><b>Check On The Latest News & Upcoming Events <i class="fa fa-hand-o-down"></i></b></h4>
    </div>
  </div>
</div>

<div class="w3-container w3-padding-16 w3-light-grey">
  <div class="w3-card w3-margin">
    <% @homes.each do |home| %>
      <div class="w3-row">
        <div class="w3-third w3-center w3-hover-grayscale" style="background-color: #07879c;">
          <h5 style="color: #ffff;"><b>Event:</b></h5>
          <p style="color: #070e1d;"><b><%= home.event %></b></p>
        </div>
        <div class="w3-third w3-center">
          <h5 style="color: #07879c;"><b>Date & Time:</b></h5>
          <p style="color: #070e1d;"><i><%= home.date_time %></i></p>
        </div>
        <div class="w3-third w3-center w3-color-2 w3-hover-grayscale w3-margin-bottom">
          <h5 style="color: #ffff;"><b>Venue:</b></h5>
          <p style="color: #070e1d;"><i><%= home.venue %></i></p>
        </div>
      </div>

      <div class="w3-display-container w3-padding-16 w3-center w3-light-grey">
        <h4 style="color: #07879c;"><b>Info:</b></h4>
        <ul class="w3-theme-border" style="list-style:none">
          <li style="color: #070e1d;"><h5><%= home.body %></h5></li>
        </ul>
      </div>
    <% end %>
  </div><br>

  <div class="level_6">
    <form action="events">
      <button type="submit" class="w3-button w3-round-large w3-theme" style="background-color: #07879c; color: #ffff"><i class="fa fa-thumbs-o-up w3-margin-right"></i> RSVP</button>
    </form> 
  </div><br><br><br>

  <div class="w3-bar w3-border w3-round">
    <a href="#" class="w3-button">&#10094; Previous</a>
    <a href="#" class="w3-button w3-right">Next &#10095;</a>
  </div>
</div>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @home.event %>
</p>

<p>
  <strong>Date time:</strong>
  <%= @home.date_time %>
</p>

<p>
  <strong>Venue:</strong>
  <%= @home.venue %>
</p>

<p>
  <strong>Body:</strong>
  <%= @home.body %>
</p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/themes/_form.html.erb
<%= form_with(model: theme, local: true) do |form| %>
  <% if theme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(theme.errors.count, "error") %> prohibited this theme from being saved:</h2>

      <ul>
      <% theme.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :demo_link %>
    <%= form.text_field :demo_link %>
  </div>

  <div class="field">
    <%= form.label :download_link %>
    <%= form.text_field :download_link %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/themes/edit.html.erb
<h1>Editing Theme</h1>

<%= render 'form', theme: @theme %>

<%= link_to 'Show', @theme %> |
<%= link_to 'Back', themes_path %>

app/views/themes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Themes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Demo link</th>
      <th>Download link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @themes.each do |theme| %>
      <tr>
        <td><%= theme.title %></td>
        <td><%= theme.demo_link %></td>
        <td><%= theme.download_link %></td>
        <td><%= link_to 'Show', theme %></td>
        <td><%= link_to 'Edit', edit_theme_path(theme) %></td>
        <td><%= link_to 'Destroy', theme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Theme', new_theme_path %>

app/views/themes/new.html.erb
<h1>New Theme</h1>

<%= render 'form', theme: @theme %>

<%= link_to 'Back', themes_path %>

app/views/themes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @theme.title %>
</p>

<p>
  <strong>Demo link:</strong>
  <%= @theme.demo_link %>
</p>

<p>
  <strong>Download link:</strong>
  <%= @theme.download_link %>
</p>

<%= link_to 'Edit', edit_theme_path(@theme) %> |
<%= link_to 'Back', themes_path %>