config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :themes
  resources :details
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :members
  resources :abouts
  resources :contacts
  resources :tutorials
  resources :homes

  root 'homes#index'
end

app/models/about.rb
class About < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :message, presence: true
end

app/models/detail.rb
class Detail < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
  validates :username, uniqueness: true, presence: true
  validates :email, uniqueness: true, presence: true, format: /\A[^@]+@[^@]+\z/
end

app/models/home.rb
class Home < ApplicationRecord
  validates :event, presence: true
  validates :date_time, presence: true
  validates :venue, presence: true
  validates :body, presence: true
end

app/models/member.rb
class Member < ApplicationRecord
  validates :username, presence: true
  validates :email, uniqueness: true, presence: true, format: /\A[^@]+@[^@]+\z/
end

app/models/theme.rb
class Theme < ApplicationRecord
end

app/models/tutorial.rb
class Tutorial < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  validates :code, presence: true
  validates :video, presence: true
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  before_action :set_about, only: [:show, :edit, :update, :destroy]

  def index
    @abouts = About.all
  end

  def show
    @about = About.find(params[:id])
    @abouts = About.order('created_at desc').limit(4).offset(1)
  end

  def new
    @about = About.new
  end

  def create
    @about = About.new(about_params)

    respond_to do |format|
      if @about.save
        format.html { redirect_to @about, notice: 'About was successfully created.' }
        format.json { render :show, status: :created, location: @about }
      else
        format.html { flash[:failure!] = 'About Not created! Verify Details & Send Again!' }
        format.html { render 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @about.update(about_params)
        format.html { redirect_to @about, notice: 'About was successfully updated.' }
        format.json { render :show, status: :ok, location: @about }
      else
        format.html { render :edit }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @about.destroy
    respond_to do |format|
      format.html { redirect_to abouts_url, notice: 'About was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_about
      @about = About.find(params[:id])
    end

    def about_params
      params.require(:about).permit(:title, :body)
    end
end

app/controllers/details_controller.rb
class DetailsController < InheritedResources::Base

  private

    def detail_params
      params.require(:detail).permit()
    end

end

app/controllers/events_controller.rb
class EventsController < InheritedResources::Base
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html do
          flash[:success] = 'Successfully Done'
          redirect_to events_url
        end
      else
        format.html { flash[:failure!] = 'Error! Verify Details!' }
        format.html { render 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html do
          flash[:success] = 'Successfully Updated'
          redirect_to events_url
        end
      else
        format.html { flash[:failure!] = 'Error! Verify Details!' }
        format.html { render 'new' }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to event_url, notice: 'Successfully Destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:username, :email, :confirm)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  def index
    @homes = Home.all
  end

  def show
    @home = Home.find(params[:id])
    @homes = Home.order('created_at desc').limit(4).offset(1)
  end

  def new
    @home = Home.new
  end

  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home Details successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { flash[:failure!] = 'Home Details Not created! Verify Details & Send Again!' }
        format.html { render 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_home
      @home = Home.find(params[:id])
    end

    def home_params
      params.require(:home).permit(:event, :date_time, :venue, :body)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/views/details/_form.html.erb
<%= form_with(model: detail, local: true) do |form| %>
  <% if detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(detail.errors.count, "error") %> prohibited this detail from being saved:</h2>

      <ul>
      <% detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/details/edit.html.erb
<h1>Editing Detail</h1>

<%= render 'form', detail: @detail %>

<%= link_to 'Show', @detail %> |
<%= link_to 'Back', details_path %>

app/views/details/index.html.erb
<div class="w3-container w3-theme-l5 w3-light-grey w3-padding-16">
  <div style="margin-left: 5%; margin-right: 5%;">
    <div class="w3-card-4 w3-margin w3-white w3-hide-small" style="width:95%;">
      <div class="w3-display-container w3-center w3-padding-64" style="background-color: #25bdd6;">
        <h3 class="w3-text-black"><b>Details About Us & What's Expected Of Our Members</b></h3>
      </div>

      <div class="w3-padding-64" style="margin-left: 5%; margin-right: 5%;">
        <h5 class="w3-text-black"><i>Wanna code, develop your simple idea from scratch to completion?? Join our community!! You'll receive the guidance & motivation in all your development endevours. Peace of mind is also guaranteed. Team work is encouraged. Developers/Problem solvers love to link up with each other. Here is a perfect platform.</i></h5>
        <h5 class="w3-text-black"><i>This community is meant for a programmer/developer, who has a passion in coding or design. Anyone be it a student/freelancer who is dealing in front-end, back-end or fullstack web or native app development and is open to learning from others or team work is welcome.</i></h5>
      </div>

      <div class="w3-row w3-padding-32">
        <div class="w3-third w3-center w3-padding-32">
          <div class="fa fa-folder-open fa-3x" style="color: #25bdd6;"></div><br><br>
          <form action="tutorials">
            <button type="submit" class="w3-button w3-round-large w3-theme" style="background-color: #07879c; color: #ffff">Tutorials</button>
          </form>
        </div>
        <div class="w3-third w3-center w3-padding-32">
          <div class="fa fa-share-square fa-3x" style="color: #25bdd6;"></div><br><br>
          <form action="themes">
            <button type="submit" class="w3-button w3-round-large w3-theme" style="background-color: #07879c; color: #ffff">Themes</button>
          </form>
        </div>
        <div class="w3-third w3-center w3-padding-32 w3-margin-bottom">
          <div class="fa fa-users fa-3x" style="color: #25bdd6;"></div><br><br>
          <form action="members">
            <button type="submit" class="w3-button w3-round-large w3-theme" style="background-color: #07879c; color: #ffff">Join</button>
          </form>
        </div>
      </div>
    </div>
  </div>

  <div style="margin-left: 0%; margin-right: 8%;">
    <div class="w3-card-4 w3-margin w3-white w3-hide-large w3-hide-medium" style="width:100%;">
      <div class="w3-display-container w3-center w3-padding-16" style="background-color: #25bdd6;">
        <h3 class="w3-text-black"><b>Details About Us & What's Expected Of Our Members</b></h3>
      </div>

      <div class="w3-padding-16" style="margin-left: 5%; margin-right: 5%;">
        <h5 class="w3-text-black"><i>Wanna code, develop your simple idea from scratch to completion?? Join our community!! You'll receive the guidance & motivation in all your development endevours. Peace of mind is also guaranteed. Team work is encouraged. Developers/Problem solvers love to link up with each other. Here is a perfect platform.</i></h5>
        <h5 class="w3-text-black"><i>This community is meant for a programmer/developer, who has a passion in coding or design. Anyone be it a student/freelancer who is dealing in front-end, back-end or fullstack web or native app development and is open to learning from others or team work is welcome.</i></h5>
      </div>

      <div class="w3-row w3-padding-16">
        <div class="w3-third w3-center w3-padding-16">
          <div class="fa fa-folder-open fa-3x" style="color: #25bdd6;"></div><br><br>
          <form action="tutorials">
            <button type="submit" class="w3-button w3-round-large w3-theme" style="background-color: #07879c; color: #ffff">Tutorials</button>
          </form>
        </div>
        <div class="w3-third w3-center w3-padding-16">
          <div class="fa fa-share-square fa-3x" style="color: #25bdd6;"></div><br><br>
          <form action="themes">
            <button type="submit" class="w3-button w3-round-large w3-theme" style="background-color: #07879c; color: #ffff">Themes</button>
          </form>
        </div>
        <div class="w3-third w3-center w3-padding-16 w3-margin-bottom">
          <div class="fa fa-users fa-3x" style="color: #25bdd6;"></div><br><br>
          <form action="members">
            <button type="submit" class="w3-button w3-round-large w3-theme" style="background-color: #07879c; color: #ffff">Community</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/details/new.html.erb
<h1>New Detail</h1>

<%= render 'form', detail: @detail %>

<%= link_to 'Back', details_path %>

app/views/details/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_detail_path(@detail) %> |
<%= link_to 'Back', details_path %>