config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :themes
  resources :details
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :members
  resources :abouts
  resources :contacts
  resources :tutorials
  resources :homes

  root 'homes#index'
end

app/models/about.rb
class About < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :message, presence: true
end

app/models/detail.rb
class Detail < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
  validates :username, uniqueness: true, presence: true
  validates :email, uniqueness: true, presence: true, format: /\A[^@]+@[^@]+\z/
end

app/models/home.rb
class Home < ApplicationRecord
  validates :event, presence: true
  validates :date_time, presence: true
  validates :venue, presence: true
  validates :body, presence: true
end

app/models/member.rb
class Member < ApplicationRecord
  validates :username, presence: true
  validates :email, uniqueness: true, presence: true, format: /\A[^@]+@[^@]+\z/
end

app/models/theme.rb
class Theme < ApplicationRecord
end

app/models/tutorial.rb
class Tutorial < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  validates :code, presence: true
  validates :video, presence: true
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  before_action :set_about, only: [:show, :edit, :update, :destroy]

  def index
    @abouts = About.all
  end

  def show
    @about = About.find(params[:id])
    @abouts = About.order('created_at desc').limit(4).offset(1)
  end

  def new
    @about = About.new
  end

  def create
    @about = About.new(about_params)

    respond_to do |format|
      if @about.save
        format.html { redirect_to @about, notice: 'About was successfully created.' }
        format.json { render :show, status: :created, location: @about }
      else
        format.html { flash[:failure!] = 'About Not created! Verify Details & Send Again!' }
        format.html { render 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @about.update(about_params)
        format.html { redirect_to @about, notice: 'About was successfully updated.' }
        format.json { render :show, status: :ok, location: @about }
      else
        format.html { render :edit }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @about.destroy
    respond_to do |format|
      format.html { redirect_to abouts_url, notice: 'About was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_about
      @about = About.find(params[:id])
    end

    def about_params
      params.require(:about).permit(:title, :body)
    end
end

app/controllers/events_controller.rb
class EventsController < InheritedResources::Base
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html do
          flash[:success] = 'Successfully Done'
          redirect_to events_url
        end
      else
        format.html { flash[:failure!] = 'Error! Verify Details!' }
        format.html { render 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html do
          flash[:success] = 'Successfully Updated'
          redirect_to events_url
        end
      else
        format.html { flash[:failure!] = 'Error! Verify Details!' }
        format.html { render 'new' }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to event_url, notice: 'Successfully Destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:username, :email, :confirm)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  def index
    @homes = Home.all
  end

  def show
    @home = Home.find(params[:id])
    @homes = Home.order('created_at desc').limit(4).offset(1)
  end

  def new
    @home = Home.new
  end

  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home Details successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { flash[:failure!] = 'Home Details Not created! Verify Details & Send Again!' }
        format.html { render 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_home
      @home = Home.find(params[:id])
    end

    def home_params
      params.require(:home).permit(:event, :date_time, :venue, :body)
    end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  def index
    @members = Member.all
  end

  def new
    @member = Member.new
  end

  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html do
          flash[:success] = 'Successfully Joined'
          redirect_to members_url
        end
      else
        format.html { flash[:failure!] = 'Error! Verify Details & Send Again!' }
        format.html { render 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Successfully Updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Successfully Destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_member
      @member = Member.find(params[:id])
    end

    def member_params
      params.require(:member).permit(:username, :email)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.number_field :phone_number %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<!-- Content Container -->
<div class="w3-container w3-padding-64 w3-theme-l5 w3-light-grey">
  <div class="w3-col m5 w3-hide-small" style="background-color: #25bdd6; margin-left: 30%;">
    <div class="w3-padding-16 w3-center">
      <span class="w3-xlarge w3-text-black"><b>Join Our Community</b></span>
    </div>

    <h5 class="w3-center" style="color: #070e1d;"><i>Join the community and receive direct communication and be part of us...</i></h5>
    <%= form_for Member.new, url: {action: "create"}, html: {class: "w3-container w3-padding-16 w3-white"} do |f| %>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>" style="color: #13a726;"><%= value %></div>
      <% end %>
      <div class="w3-section"> 
        <%= f.text_field :username, class: 'w3-input', placeholder: 'UserName'%>
      </div>
      <div class="w3-section">      
        <%= f.text_field :email, class: 'w3-input', placeholder: 'Email'%>
      </div>
      <button type="submit" class="w3-button w3-round-large w3-theme fa fa-user" style="background-color: #07879c; color: #ffff"> Join</button>
    <% end %>
  </div>

  <div class="w3-col m5 w3-hide-medium w3-hide-large" style="background-color: #25bdd6;">
    <div class="w3-padding-16 w3-center">
      <span class="w3-xlarge w3-text-black"><b>Join Our Community</b></span>
    </div>

    <h5 class="w3-center" style="color: #070e1d;"><i>Join the community and receive direct communication and be part of us...</i></h5>
    <%= form_for Member.new, url: {action: "create"}, html: {class: "w3-container w3-padding-16 w3-white"} do |f| %>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>" style="color: #13a726;"><%= value %></div>
      <% end %>
      <div class="w3-section"> 
        <%= f.text_field :username, class: 'w3-input', placeholder: 'UserName'%>
      </div>
      <div class="w3-section">      
        <%= f.text_field :email, class: 'w3-input', placeholder: 'Email'%>
      </div>
      <button type="submit" class="w3-button w3-round-large w3-theme fa fa-user" style="background-color: #07879c; color: #ffff"> Join</button>
    <% end %>
  </div>
</div>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @member.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @member.last_name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @member.phone_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @member.email %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>